# coding: utf-8

# flake8: noqa
"""
    LaunchDarkly REST API

    This documentation describes LaunchDarkly's REST API. To access the complete OpenAPI spec directly, use [Get OpenAPI spec](https://launchdarkly.com/docs/api/other/get-openapi-spec).  To learn how to use LaunchDarkly using the user interface (UI) instead, read our [product documentation](https://launchdarkly.com/docs/home).  ## Authentication  LaunchDarkly's REST API uses the HTTPS protocol with a minimum TLS version of 1.2.  All REST API resources are authenticated with either [personal or service access tokens](https://launchdarkly.com/docs/home/account/api), or session cookies. Other authentication mechanisms are not supported. You can manage personal access tokens on your [**Authorization**](https://app.launchdarkly.com/settings/authorization) page in the LaunchDarkly UI.  LaunchDarkly also has SDK keys, mobile keys, and client-side IDs that are used by our server-side SDKs, mobile SDKs, and JavaScript-based SDKs, respectively. **These keys cannot be used to access our REST API**. These keys are environment-specific, and can only perform read-only operations such as fetching feature flag settings.  | Auth mechanism                                                                                  | Allowed resources                                                                                     | Use cases                                          | | ----------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------- | -------------------------------------------------- | | [Personal or service access tokens](https://launchdarkly.com/docs/home/account/api) | Can be customized on a per-token basis                                                                | Building scripts, custom integrations, data export. | | SDK keys                                                                                        | Can only access read-only resources specific to server-side SDKs. Restricted to a single environment. | Server-side SDKs                     | | Mobile keys                                                                                     | Can only access read-only resources specific to mobile SDKs, and only for flags marked available to mobile keys. Restricted to a single environment.           | Mobile SDKs                                        | | Client-side ID                                                                                  | Can only access read-only resources specific to JavaScript-based client-side SDKs, and only for flags marked available to client-side. Restricted to a single environment.           | Client-side JavaScript                             |  > #### Keep your access tokens and SDK keys private > > Access tokens should _never_ be exposed in untrusted contexts. Never put an access token in client-side JavaScript, or embed it in a mobile application. LaunchDarkly has special mobile keys that you can embed in mobile apps. If you accidentally expose an access token or SDK key, you can reset it from your [**Authorization**](https://app.launchdarkly.com/settings/authorization) page. > > The client-side ID is safe to embed in untrusted contexts. It's designed for use in client-side JavaScript.  ### Authentication using request header  The preferred way to authenticate with the API is by adding an `Authorization` header containing your access token to your requests. The value of the `Authorization` header must be your access token.  Manage personal access tokens from the [**Authorization**](https://app.launchdarkly.com/settings/authorization) page.  ### Authentication using session cookie  For testing purposes, you can make API calls directly from your web browser. If you are logged in to the LaunchDarkly application, the API will use your existing session to authenticate calls.  Depending on the permissions granted as part of your [role](https://launchdarkly.com/docs/home/account/roles), you may not have permission to perform some API calls. You will receive a `401` response code in that case.  > ### Modifying the Origin header causes an error > > LaunchDarkly validates that the Origin header for any API request authenticated by a session cookie matches the expected Origin header. The expected Origin header is `https://app.launchdarkly.com`. > > If the Origin header does not match what's expected, LaunchDarkly returns an error. This error can prevent the LaunchDarkly app from working correctly. > > Any browser extension that intentionally changes the Origin header can cause this problem. For example, the `Allow-Control-Allow-Origin: *` Chrome extension changes the Origin header to `http://evil.com` and causes the app to fail. > > To prevent this error, do not modify your Origin header. > > LaunchDarkly does not require origin matching when authenticating with an access token, so this issue does not affect normal API usage.  ## Representations  All resources expect and return JSON response bodies. Error responses also send a JSON body. To learn more about the error format of the API, read [Errors](https://launchdarkly.com/docs/api#errors).  In practice this means that you always get a response with a `Content-Type` header set to `application/json`.  In addition, request bodies for `PATCH`, `POST`, and `PUT` requests must be encoded as JSON with a `Content-Type` header set to `application/json`.  ### Summary and detailed representations  When you fetch a list of resources, the response includes only the most important attributes of each resource. This is a _summary representation_ of the resource. When you fetch an individual resource, such as a single feature flag, you receive a _detailed representation_ of the resource.  The best way to find a detailed representation is to follow links. Every summary representation includes a link to its detailed representation.  ### Expanding responses  Sometimes the detailed representation of a resource does not include all of the attributes of the resource by default. If this is the case, the request method will clearly document this and describe which attributes you can include in an expanded response.  To include the additional attributes, append the `expand` request parameter to your request and add a comma-separated list of the attributes to include. For example, when you append `?expand=members,maintainers` to the [Get team](https://launchdarkly.com/docs/api/teams/get-team) endpoint, the expanded response includes both of these attributes.  ### Links and addressability  The best way to navigate the API is by following links. These are attributes in representations that link to other resources. The API always uses the same format for links:  - Links to other resources within the API are encapsulated in a `_links` object - If the resource has a corresponding link to HTML content on the site, it is stored in a special `_site` link  Each link has two attributes:  - An `href`, which contains the URL - A `type`, which describes the content type  For example, a feature resource might return the following:  ```json {   \"_links\": {     \"parent\": {       \"href\": \"/api/features\",       \"type\": \"application/json\"     },     \"self\": {       \"href\": \"/api/features/sort.order\",       \"type\": \"application/json\"     }   },   \"_site\": {     \"href\": \"/features/sort.order\",     \"type\": \"text/html\"   } } ```  From this, you can navigate to the parent collection of features by following the `parent` link, or navigate to the site page for the feature by following the `_site` link.  Collections are always represented as a JSON object with an `items` attribute containing an array of representations. Like all other representations, collections have `_links` defined at the top level.  Paginated collections include `first`, `last`, `next`, and `prev` links containing a URL with the respective set of elements in the collection.  ## Updates  Resources that accept partial updates use the `PATCH` verb. Most resources support the [JSON patch](https://launchdarkly.com/docs/api#updates-using-json-patch) format. Some resources also support the [JSON merge patch](https://launchdarkly.com/docs/api#updates-using-json-merge-patch) format, and some resources support the [semantic patch](https://launchdarkly.com/docs/api#updates-using-semantic-patch) format, which is a way to specify the modifications to perform as a set of executable instructions. Each resource supports optional [comments](https://launchdarkly.com/docs/api#updates-with-comments) that you can submit with updates. Comments appear in outgoing webhooks, the audit log, and other integrations.  When a resource supports both JSON patch and semantic patch, we document both in the request method. However, the specific request body fields and descriptions included in our documentation only match one type of patch or the other.  ### Updates using JSON patch  [JSON patch](https://datatracker.ietf.org/doc/html/rfc6902) is a way to specify the modifications to perform on a resource. JSON patch uses paths and a limited set of operations to describe how to transform the current state of the resource into a new state. JSON patch documents are always arrays, where each element contains an operation, a path to the field to update, and the new value.  For example, in this feature flag representation:  ```json {     \"name\": \"New recommendations engine\",     \"key\": \"engine.enable\",     \"description\": \"This is the description\",     ... } ``` You can change the feature flag's description with the following patch document:  ```json [{ \"op\": \"replace\", \"path\": \"/description\", \"value\": \"This is the new description\" }] ```  You can specify multiple modifications to perform in a single request. You can also test that certain preconditions are met before applying the patch:  ```json [   { \"op\": \"test\", \"path\": \"/version\", \"value\": 10 },   { \"op\": \"replace\", \"path\": \"/description\", \"value\": \"The new description\" } ] ```  The above patch request tests whether the feature flag's `version` is `10`, and if so, changes the feature flag's description.  Attributes that are not editable, such as a resource's `_links`, have names that start with an underscore.  ### Updates using JSON merge patch  [JSON merge patch](https://datatracker.ietf.org/doc/html/rfc7386) is another format for specifying the modifications to perform on a resource. JSON merge patch is less expressive than JSON patch. However, in many cases it is simpler to construct a merge patch document. For example, you can change a feature flag's description with the following merge patch document:  ```json {   \"description\": \"New flag description\" } ```  ### Updates using semantic patch  Some resources support the semantic patch format. A semantic patch is a way to specify the modifications to perform on a resource as a set of executable instructions.  Semantic patch allows you to be explicit about intent using precise, custom instructions. In many cases, you can define semantic patch instructions independently of the current state of the resource. This can be useful when defining a change that may be applied at a future date.  To make a semantic patch request, you must append `domain-model=launchdarkly.semanticpatch` to your `Content-Type` header.  Here's how:  ``` Content-Type: application/json; domain-model=launchdarkly.semanticpatch ```  If you call a semantic patch resource without this header, you will receive a `400` response because your semantic patch will be interpreted as a JSON patch.  The body of a semantic patch request takes the following properties:  * `comment` (string): (Optional) A description of the update. * `environmentKey` (string): (Required for some resources only) The environment key. * `instructions` (array): (Required) A list of actions the update should perform. Each action in the list must be an object with a `kind` property that indicates the instruction. If the instruction requires parameters, you must include those parameters as additional fields in the object. The documentation for each resource that supports semantic patch includes the available instructions and any additional parameters.  For example:  ```json {   \"comment\": \"optional comment\",   \"instructions\": [ {\"kind\": \"turnFlagOn\"} ] } ```  Semantic patches are not applied partially; either all of the instructions are applied or none of them are. If **any** instruction is invalid, the endpoint returns an error and will not change the resource. If all instructions are valid, the request succeeds and the resources are updated if necessary, or left unchanged if they are already in the state you request.  ### Updates with comments  You can submit optional comments with `PATCH` changes.  To submit a comment along with a JSON patch document, use the following format:  ```json {   \"comment\": \"This is a comment string\",   \"patch\": [{ \"op\": \"replace\", \"path\": \"/description\", \"value\": \"The new description\" }] } ```  To submit a comment along with a JSON merge patch document, use the following format:  ```json {   \"comment\": \"This is a comment string\",   \"merge\": { \"description\": \"New flag description\" } } ```  To submit a comment along with a semantic patch, use the following format:  ```json {   \"comment\": \"This is a comment string\",   \"instructions\": [ {\"kind\": \"turnFlagOn\"} ] } ```  ## Errors  The API always returns errors in a common format. Here's an example:  ```json {   \"code\": \"invalid_request\",   \"message\": \"A feature with that key already exists\",   \"id\": \"30ce6058-87da-11e4-b116-123b93f75cba\" } ```  The `code` indicates the general class of error. The `message` is a human-readable explanation of what went wrong. The `id` is a unique identifier. Use it when you're working with LaunchDarkly Support to debug a problem with a specific API call.  ### HTTP status error response codes  | Code | Definition        | Description                                                                                       | Possible Solution                                                | | ---- | ----------------- | ------------------------------------------------------------------------------------------- | ---------------------------------------------------------------- | | 400  | Invalid request       | The request cannot be understood.                                    | Ensure JSON syntax in request body is correct.                   | | 401  | Invalid access token      | Requestor is unauthorized or does not have permission for this API call.                                                | Ensure your API access token is valid and has the appropriate permissions.                                     | | 403  | Forbidden         | Requestor does not have access to this resource.                                                | Ensure that the account member or access token has proper permissions set. | | 404  | Invalid resource identifier | The requested resource is not valid. | Ensure that the resource is correctly identified by ID or key. | | 405  | Method not allowed | The request method is not allowed on this resource. | Ensure that the HTTP verb is correct. | | 409  | Conflict          | The API request can not be completed because it conflicts with a concurrent API request. | Retry your request.                                              | | 422  | Unprocessable entity | The API request can not be completed because the update description can not be understood. | Ensure that the request body is correct for the type of patch you are using, either JSON patch or semantic patch. | 429  | Too many requests | Read [Rate limiting](https://launchdarkly.com/docs/api#rate-limiting).                                               | Wait and try again later.                                        |  ## CORS  The LaunchDarkly API supports Cross Origin Resource Sharing (CORS) for AJAX requests from any origin. If an `Origin` header is given in a request, it will be echoed as an explicitly allowed origin. Otherwise the request returns a wildcard, `Access-Control-Allow-Origin: *`. For more information on CORS, read the [CORS W3C Recommendation](http://www.w3.org/TR/cors). Example CORS headers might look like:  ```http Access-Control-Allow-Headers: Accept, Content-Type, Content-Length, Accept-Encoding, Authorization Access-Control-Allow-Methods: OPTIONS, GET, DELETE, PATCH Access-Control-Allow-Origin: * Access-Control-Max-Age: 300 ```  You can make authenticated CORS calls just as you would make same-origin calls, using either [token or session-based authentication](https://launchdarkly.com/docs/api#authentication). If you are using session authentication, you should set the `withCredentials` property for your `xhr` request to `true`. You should never expose your access tokens to untrusted entities.  ## Rate limiting  We use several rate limiting strategies to ensure the availability of our APIs. Rate-limited calls to our APIs return a `429` status code. Calls to our APIs include headers indicating the current rate limit status. The specific headers returned depend on the API route being called. The limits differ based on the route, authentication mechanism, and other factors. Routes that are not rate limited may not contain any of the headers described below.  > ### Rate limiting and SDKs > > LaunchDarkly SDKs are never rate limited and do not use the API endpoints defined here. LaunchDarkly uses a different set of approaches, including streaming/server-sent events and a global CDN, to ensure availability to the routes used by LaunchDarkly SDKs.  ### Global rate limits  Authenticated requests are subject to a global limit. This is the maximum number of calls that your account can make to the API per ten seconds. All service and personal access tokens on the account share this limit, so exceeding the limit with one access token will impact other tokens. Calls that are subject to global rate limits may return the headers below:  | Header name                    | Description                                                                      | | ------------------------------ | -------------------------------------------------------------------------------- | | `X-Ratelimit-Global-Remaining` | The maximum number of requests the account is permitted to make per ten seconds. | | `X-Ratelimit-Reset`            | The time at which the current rate limit window resets in epoch milliseconds.    |  We do not publicly document the specific number of calls that can be made globally. This limit may change, and we encourage clients to program against the specification, relying on the two headers defined above, rather than hardcoding to the current limit.  ### Route-level rate limits  Some authenticated routes have custom rate limits. These also reset every ten seconds. Any service or personal access tokens hitting the same route share this limit, so exceeding the limit with one access token may impact other tokens. Calls that are subject to route-level rate limits return the headers below:  | Header name                   | Description                                                                                           | | ----------------------------- | ----------------------------------------------------------------------------------------------------- | | `X-Ratelimit-Route-Remaining` | The maximum number of requests to the current route the account is permitted to make per ten seconds. | | `X-Ratelimit-Reset`           | The time at which the current rate limit window resets in epoch milliseconds.                         |  A _route_ represents a specific URL pattern and verb. For example, the [Delete environment](https://launchdarkly.com/docs/api/environments/delete-environment) endpoint is considered a single route, and each call to delete an environment counts against your route-level rate limit for that route.  We do not publicly document the specific number of calls that an account can make to each endpoint per ten seconds. These limits may change, and we encourage clients to program against the specification, relying on the two headers defined above, rather than hardcoding to the current limits.  ### IP-based rate limiting  We also employ IP-based rate limiting on some API routes. If you hit an IP-based rate limit, your API response will include a `Retry-After` header indicating how long to wait before re-trying the call. Clients must wait at least `Retry-After` seconds before making additional calls to our API, and should employ jitter and backoff strategies to avoid triggering rate limits again.  ## OpenAPI (Swagger) and client libraries  We have a [complete OpenAPI (Swagger) specification](https://app.launchdarkly.com/api/v2/openapi.json) for our API.  We auto-generate multiple client libraries based on our OpenAPI specification. To learn more, visit the [collection of client libraries on GitHub](https://github.com/search?q=topic%3Alaunchdarkly-api+org%3Alaunchdarkly&type=Repositories). You can also use this specification to generate client libraries to interact with our REST API in your language of choice.  Our OpenAPI specification is supported by several API-based tools such as Postman and Insomnia. In many cases, you can directly import our specification to explore our APIs.  ## Method overriding  Some firewalls and HTTP clients restrict the use of verbs other than `GET` and `POST`. In those environments, our API endpoints that use `DELETE`, `PATCH`, and `PUT` verbs are inaccessible.  To avoid this issue, our API supports the `X-HTTP-Method-Override` header, allowing clients to \"tunnel\" `DELETE`, `PATCH`, and `PUT` requests using a `POST` request.  For example, to call a `PATCH` endpoint using a `POST` request, you can include `X-HTTP-Method-Override:PATCH` as a header.  ## Beta resources  We sometimes release new API resources in **beta** status before we release them with general availability.  Resources that are in beta are still undergoing testing and development. They may change without notice, including becoming backwards incompatible.  We try to promote resources into general availability as quickly as possible. This happens after sufficient testing and when we're satisfied that we no longer need to make backwards-incompatible changes.  We mark beta resources with a \"Beta\" callout in our documentation, pictured below:  > ### This feature is in beta > > To use this feature, pass in a header including the `LD-API-Version` key with value set to `beta`. Use this header with each call. To learn more, read [Beta resources](https://launchdarkly.com/docs/api#beta-resources). > > Resources that are in beta are still undergoing testing and development. They may change without notice, including becoming backwards incompatible.  ### Using beta resources  To use a beta resource, you must include a header in the request. If you call a beta resource without this header, you receive a `403` response.  Use this header:  ``` LD-API-Version: beta ```  ## Federal and EU environments  In addition to the commercial versions, LaunchDarkly offers instances for federal agencies and those based in the European Union (EU).  ### Federal environments  The version of LaunchDarkly that is available on domains controlled by the United States government is different from the version of LaunchDarkly available to the general public. If you are an employee or contractor for a United States federal agency and use LaunchDarkly in your work, you likely use the federal instance of LaunchDarkly.  If you are working in the federal instance of LaunchDarkly, the base URI for each request is `https://app.launchdarkly.us`.  To learn more, read [LaunchDarkly in federal environments](https://launchdarkly.com/docs/home/infrastructure/federal).  ### EU environments  The version of LaunchDarkly that is available in the EU is different from the version of LaunchDarkly available to other regions. If you are based in the EU, you likely use the EU instance of LaunchDarkly. The LaunchDarkly EU instance complies with EU data residency principles, including the protection and confidentiality of EU customer information.  If you are working in the EU instance of LaunchDarkly, the base URI for each request is `https://app.eu.launchdarkly.com`.  To learn more, read [LaunchDarkly in the European Union (EU)](https://launchdarkly.com/docs/home/infrastructure/eu).  ## Versioning  We try hard to keep our REST API backwards compatible, but we occasionally have to make backwards-incompatible changes in the process of shipping new features. These breaking changes can cause unexpected behavior if you don't prepare for them accordingly.  Updates to our REST API include support for the latest features in LaunchDarkly. We also release a new version of our REST API every time we make a breaking change. We provide simultaneous support for multiple API versions so you can migrate from your current API version to a new version at your own pace.  ### Setting the API version per request  You can set the API version on a specific request by sending an `LD-API-Version` header, as shown in the example below:  ``` LD-API-Version: 20240415 ```  The header value is the version number of the API version you would like to request. The number for each version corresponds to the date the version was released in `yyyymmdd` format. In the example above the version `20240415` corresponds to April 15, 2024.  ### Setting the API version per access token  When you create an access token, you must specify a specific version of the API to use. This ensures that integrations using this token cannot be broken by version changes.  Tokens created before versioning was released have their version set to `20160426`, which is the version of the API that existed before the current versioning scheme, so that they continue working the same way they did before versioning.  If you would like to upgrade your integration to use a new API version, you can explicitly set the header described above.  > ### Best practice: Set the header for every client or integration > > We recommend that you set the API version header explicitly in any client or integration you build. > > Only rely on the access token API version during manual testing.  ### API version changelog  <table>   <tr>     <th>Version</th>     <th>Changes</th>     <th>End of life (EOL)</th>   </tr>   <tr>     <td>`20240415`</td>     <td>       <ul><li>Changed several endpoints from unpaginated to paginated. Use the `limit` and `offset` query parameters to page through the results.</li> <li>Changed the [list access tokens](https://launchdarkly.com/docs/api/access-tokens/get-tokens) endpoint: <ul><li>Response is now paginated with a default limit of `25`</li></ul></li> <li>Changed the [list account members](https://launchdarkly.com/docs/api/account-members/get-members) endpoint: <ul><li>The `accessCheck` filter is no longer available</li></ul></li> <li>Changed the [list custom roles](https://launchdarkly.com/docs/api/custom-roles/get-custom-roles) endpoint: <ul><li>Response is now paginated with a default limit of `20`</li></ul></li> <li>Changed the [list feature flags](https://launchdarkly.com/docs/api/feature-flags/get-feature-flags) endpoint: <ul><li>Response is now paginated with a default limit of `20`</li><li>The `environments` field is now only returned if the request is filtered by environment, using the `filterEnv` query parameter</li><li>The `followerId`, `hasDataExport`, `status`, `contextKindTargeted`, and `segmentTargeted` filters are no longer available</li><li>The `compare` query parameter is no longer available</li></ul></li> <li>Changed the [list segments](https://launchdarkly.com/docs/api/segments/get-segments) endpoint: <ul><li>Response is now paginated with a default limit of `20`</li></ul></li> <li>Changed the [list teams](https://launchdarkly.com/docs/api/teams/get-teams) endpoint: <ul><li>The `expand` parameter no longer supports including `projects` or `roles`</li><li>In paginated results, the maximum page size is now 100</li></ul></li> <li>Changed the [get workflows](https://launchdarkly.com/docs/api/workflows/get-workflows) endpoint: <ul><li>Response is now paginated with a default limit of `20`</li><li>The `_conflicts` field in the response is no longer available</li></ul></li> </ul>     </td>     <td>Current</td>   </tr>   <tr>     <td>`20220603`</td>     <td>       <ul><li>Changed the [list projects](https://launchdarkly.com/docs/api/projects/get-projects) return value:<ul><li>Response is now paginated with a default limit of `20`.</li><li>Added support for filter and sort.</li><li>The project `environments` field is now expandable. This field is omitted by default.</li></ul></li><li>Changed the [get project](https://launchdarkly.com/docs/api/projects/get-project) return value:<ul><li>The `environments` field is now expandable. This field is omitted by default.</li></ul></li></ul>     </td>     <td>2025-04-15</td>   </tr>   <tr>     <td>`20210729`</td>     <td>       <ul><li>Changed the [create approval request](https://launchdarkly.com/docs/api/approvals/post-approval-request) return value. It now returns HTTP Status Code `201` instead of `200`.</li><li> Changed the [get user](https://launchdarkly.com/docs/api/users/get-user) return value. It now returns a user record, not a user. </li><li>Added additional optional fields to environment, segments, flags, members, and segments, including the ability to create big segments. </li><li> Added default values for flag variations when new environments are created. </li><li>Added filtering and pagination for getting flags and members, including `limit`, `number`, `filter`, and `sort` query parameters. </li><li>Added endpoints for expiring user targets for flags and segments, scheduled changes, access tokens, Relay Proxy configuration, integrations and subscriptions, and approvals. </li></ul>     </td>     <td>2023-06-03</td>   </tr>   <tr>     <td>`20191212`</td>     <td>       <ul><li>[List feature flags](https://launchdarkly.com/docs/api/feature-flags/get-feature-flags) now defaults to sending summaries of feature flag configurations, equivalent to setting the query parameter `summary=true`. Summaries omit flag targeting rules and individual user targets from the payload. </li><li> Added endpoints for flags, flag status, projects, environments, audit logs, members, users, custom roles, segments, usage, streams, events, and data export. </li></ul>     </td>     <td>2022-07-29</td>   </tr>   <tr>     <td>`20160426`</td>     <td>       <ul><li>Initial versioning of API. Tokens created before versioning have their version set to this.</li></ul>     </td>     <td>2020-12-12</td>   </tr> </table>  To learn more about how EOL is determined, read LaunchDarkly's [End of Life (EOL) Policy](https://launchdarkly.com/policies/end-of-life-policy/). 

    The version of the OpenAPI document: 2.0
    Contact: support@launchdarkly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from launchdarkly_api.models.ai_config import AIConfig
from launchdarkly_api.models.ai_config_maintainer import AIConfigMaintainer
from launchdarkly_api.models.ai_config_patch import AIConfigPatch
from launchdarkly_api.models.ai_config_post import AIConfigPost
from launchdarkly_api.models.ai_config_rep import AIConfigRep
from launchdarkly_api.models.ai_config_targeting import AIConfigTargeting
from launchdarkly_api.models.ai_config_targeting_defaults import AIConfigTargetingDefaults
from launchdarkly_api.models.ai_config_targeting_environment import AIConfigTargetingEnvironment
from launchdarkly_api.models.ai_config_targeting_environment_fallthrough import AIConfigTargetingEnvironmentFallthrough
from launchdarkly_api.models.ai_config_targeting_environment_fallthrough_rollout import AIConfigTargetingEnvironmentFallthroughRollout
from launchdarkly_api.models.ai_config_targeting_environment_fallthrough_rollout_experimentation_allocation import AIConfigTargetingEnvironmentFallthroughRolloutExperimentationAllocation
from launchdarkly_api.models.ai_config_targeting_environment_fallthrough_rollout_variation import AIConfigTargetingEnvironmentFallthroughRolloutVariation
from launchdarkly_api.models.ai_config_targeting_environment_rule import AIConfigTargetingEnvironmentRule
from launchdarkly_api.models.ai_config_targeting_environment_rule_clause import AIConfigTargetingEnvironmentRuleClause
from launchdarkly_api.models.ai_config_targeting_environment_target import AIConfigTargetingEnvironmentTarget
from launchdarkly_api.models.ai_config_targeting_patch import AIConfigTargetingPatch
from launchdarkly_api.models.ai_config_targeting_variation import AIConfigTargetingVariation
from launchdarkly_api.models.ai_config_targeting_variation_value import AIConfigTargetingVariationValue
from launchdarkly_api.models.ai_config_variation import AIConfigVariation
from launchdarkly_api.models.ai_config_variation_patch import AIConfigVariationPatch
from launchdarkly_api.models.ai_config_variation_post import AIConfigVariationPost
from launchdarkly_api.models.ai_config_variations_response import AIConfigVariationsResponse
from launchdarkly_api.models.ai_configs import AIConfigs
from launchdarkly_api.models.ai_configs_summary import AIConfigsSummary
from launchdarkly_api.models.ai_tool import AITool
from launchdarkly_api.models.ai_tool_patch import AIToolPatch
from launchdarkly_api.models.ai_tool_post import AIToolPost
from launchdarkly_api.models.ai_tools import AITools
from launchdarkly_api.models.access import Access
from launchdarkly_api.models.access_allowed_reason import AccessAllowedReason
from launchdarkly_api.models.access_allowed_rep import AccessAllowedRep
from launchdarkly_api.models.access_denied import AccessDenied
from launchdarkly_api.models.access_denied_reason import AccessDeniedReason
from launchdarkly_api.models.access_token_post import AccessTokenPost
from launchdarkly_api.models.action_input import ActionInput
from launchdarkly_api.models.action_output import ActionOutput
from launchdarkly_api.models.agent_graph import AgentGraph
from launchdarkly_api.models.agent_graph_edge import AgentGraphEdge
from launchdarkly_api.models.agent_graph_edge_post import AgentGraphEdgePost
from launchdarkly_api.models.agent_graph_patch import AgentGraphPatch
from launchdarkly_api.models.agent_graph_post import AgentGraphPost
from launchdarkly_api.models.agent_graphs import AgentGraphs
from launchdarkly_api.models.ai_configs_access import AiConfigsAccess
from launchdarkly_api.models.ai_configs_access_allowed_reason import AiConfigsAccessAllowedReason
from launchdarkly_api.models.ai_configs_access_allowed_rep import AiConfigsAccessAllowedRep
from launchdarkly_api.models.ai_configs_access_denied import AiConfigsAccessDenied
from launchdarkly_api.models.ai_configs_access_denied_reason import AiConfigsAccessDeniedReason
from launchdarkly_api.models.ai_configs_experiment_enabled_period_rep import AiConfigsExperimentEnabledPeriodRep
from launchdarkly_api.models.ai_configs_experiment_environment_setting_rep import AiConfigsExperimentEnvironmentSettingRep
from launchdarkly_api.models.ai_configs_experiment_info_rep import AiConfigsExperimentInfoRep
from launchdarkly_api.models.ai_configs_filter import AiConfigsFilter
from launchdarkly_api.models.ai_configs_legacy_experiment_rep import AiConfigsLegacyExperimentRep
from launchdarkly_api.models.ai_configs_link import AiConfigsLink
from launchdarkly_api.models.ai_configs_maintainer_team import AiConfigsMaintainerTeam
from launchdarkly_api.models.ai_configs_member_summary import AiConfigsMemberSummary
from launchdarkly_api.models.ai_configs_metric_data_source_ref_rep import AiConfigsMetricDataSourceRefRep
from launchdarkly_api.models.ai_configs_metric_event_default_rep import AiConfigsMetricEventDefaultRep
from launchdarkly_api.models.ai_configs_metric_listing_rep import AiConfigsMetricListingRep
from launchdarkly_api.models.ai_configs_modification import AiConfigsModification
from launchdarkly_api.models.announcement_access import AnnouncementAccess
from launchdarkly_api.models.announcement_access_allowed_reason import AnnouncementAccessAllowedReason
from launchdarkly_api.models.announcement_access_allowed_rep import AnnouncementAccessAllowedRep
from launchdarkly_api.models.announcement_access_denied import AnnouncementAccessDenied
from launchdarkly_api.models.announcement_access_denied_reason import AnnouncementAccessDeniedReason
from launchdarkly_api.models.announcement_access_rep import AnnouncementAccessRep
from launchdarkly_api.models.announcement_link import AnnouncementLink
from launchdarkly_api.models.announcement_paginated_links import AnnouncementPaginatedLinks
from launchdarkly_api.models.announcement_patch_operation import AnnouncementPatchOperation
from launchdarkly_api.models.announcement_response import AnnouncementResponse
from launchdarkly_api.models.announcement_response_links import AnnouncementResponseLinks
from launchdarkly_api.models.application_collection_rep import ApplicationCollectionRep
from launchdarkly_api.models.application_flag_collection_rep import ApplicationFlagCollectionRep
from launchdarkly_api.models.application_rep import ApplicationRep
from launchdarkly_api.models.application_version_rep import ApplicationVersionRep
from launchdarkly_api.models.application_versions_collection_rep import ApplicationVersionsCollectionRep
from launchdarkly_api.models.approval_request_response import ApprovalRequestResponse
from launchdarkly_api.models.approval_request_setting import ApprovalRequestSetting
from launchdarkly_api.models.approval_request_setting_with_envs import ApprovalRequestSettingWithEnvs
from launchdarkly_api.models.approval_request_settings_patch import ApprovalRequestSettingsPatch
from launchdarkly_api.models.approval_settings import ApprovalSettings
from launchdarkly_api.models.approvals_capability_config import ApprovalsCapabilityConfig
from launchdarkly_api.models.assigned_to_rep import AssignedToRep
from launchdarkly_api.models.audience import Audience
from launchdarkly_api.models.audience_configuration import AudienceConfiguration
from launchdarkly_api.models.audience_post import AudiencePost
from launchdarkly_api.models.audit_log_entry_listing_rep import AuditLogEntryListingRep
from launchdarkly_api.models.audit_log_entry_listing_rep_collection import AuditLogEntryListingRepCollection
from launchdarkly_api.models.audit_log_entry_rep import AuditLogEntryRep
from launchdarkly_api.models.audit_log_events_hook_capability_config_post import AuditLogEventsHookCapabilityConfigPost
from launchdarkly_api.models.audit_log_events_hook_capability_config_rep import AuditLogEventsHookCapabilityConfigRep
from launchdarkly_api.models.authorized_app_data_rep import AuthorizedAppDataRep
from launchdarkly_api.models.big_segment_store_integration import BigSegmentStoreIntegration
from launchdarkly_api.models.big_segment_store_integration_collection import BigSegmentStoreIntegrationCollection
from launchdarkly_api.models.big_segment_store_integration_collection_links import BigSegmentStoreIntegrationCollectionLinks
from launchdarkly_api.models.big_segment_store_integration_links import BigSegmentStoreIntegrationLinks
from launchdarkly_api.models.big_segment_store_status import BigSegmentStoreStatus
from launchdarkly_api.models.big_segment_target import BigSegmentTarget
from launchdarkly_api.models.boolean_defaults import BooleanDefaults
from launchdarkly_api.models.boolean_flag_defaults import BooleanFlagDefaults
from launchdarkly_api.models.branch_collection_rep import BranchCollectionRep
from launchdarkly_api.models.branch_rep import BranchRep
from launchdarkly_api.models.bulk_edit_members_rep import BulkEditMembersRep
from launchdarkly_api.models.bulk_edit_teams_rep import BulkEditTeamsRep
from launchdarkly_api.models.caller_identity_rep import CallerIdentityRep
from launchdarkly_api.models.capability_config_post import CapabilityConfigPost
from launchdarkly_api.models.capability_config_rep import CapabilityConfigRep
from launchdarkly_api.models.clause import Clause
from launchdarkly_api.models.client import Client
from launchdarkly_api.models.client_collection import ClientCollection
from launchdarkly_api.models.client_side_availability import ClientSideAvailability
from launchdarkly_api.models.client_side_availability_post import ClientSideAvailabilityPost
from launchdarkly_api.models.completed_by import CompletedBy
from launchdarkly_api.models.condition_input import ConditionInput
from launchdarkly_api.models.condition_output import ConditionOutput
from launchdarkly_api.models.conflict import Conflict
from launchdarkly_api.models.conflict_output import ConflictOutput
from launchdarkly_api.models.context_attribute_name import ContextAttributeName
from launchdarkly_api.models.context_attribute_names import ContextAttributeNames
from launchdarkly_api.models.context_attribute_names_collection import ContextAttributeNamesCollection
from launchdarkly_api.models.context_attribute_value import ContextAttributeValue
from launchdarkly_api.models.context_attribute_values import ContextAttributeValues
from launchdarkly_api.models.context_attribute_values_collection import ContextAttributeValuesCollection
from launchdarkly_api.models.context_instance_evaluation import ContextInstanceEvaluation
from launchdarkly_api.models.context_instance_evaluation_reason import ContextInstanceEvaluationReason
from launchdarkly_api.models.context_instance_evaluations import ContextInstanceEvaluations
from launchdarkly_api.models.context_instance_record import ContextInstanceRecord
from launchdarkly_api.models.context_instance_search import ContextInstanceSearch
from launchdarkly_api.models.context_instance_segment_membership import ContextInstanceSegmentMembership
from launchdarkly_api.models.context_instance_segment_memberships import ContextInstanceSegmentMemberships
from launchdarkly_api.models.context_instances import ContextInstances
from launchdarkly_api.models.context_kind_rep import ContextKindRep
from launchdarkly_api.models.context_kinds_collection_rep import ContextKindsCollectionRep
from launchdarkly_api.models.context_record import ContextRecord
from launchdarkly_api.models.context_search import ContextSearch
from launchdarkly_api.models.contexts import Contexts
from launchdarkly_api.models.copied_from_env import CopiedFromEnv
from launchdarkly_api.models.core_link import CoreLink
from launchdarkly_api.models.create_announcement_body import CreateAnnouncementBody
from launchdarkly_api.models.create_approval_request_request import CreateApprovalRequestRequest
from launchdarkly_api.models.create_copy_flag_config_approval_request_request import CreateCopyFlagConfigApprovalRequestRequest
from launchdarkly_api.models.create_flag_config_approval_request_request import CreateFlagConfigApprovalRequestRequest
from launchdarkly_api.models.create_phase_input import CreatePhaseInput
from launchdarkly_api.models.create_release_input import CreateReleaseInput
from launchdarkly_api.models.create_release_pipeline_input import CreateReleasePipelineInput
from launchdarkly_api.models.create_workflow_template_input import CreateWorkflowTemplateInput
from launchdarkly_api.models.custom_property import CustomProperty
from launchdarkly_api.models.custom_role import CustomRole
from launchdarkly_api.models.custom_role_post import CustomRolePost
from launchdarkly_api.models.custom_roles import CustomRoles
from launchdarkly_api.models.custom_workflow_input import CustomWorkflowInput
from launchdarkly_api.models.custom_workflow_meta import CustomWorkflowMeta
from launchdarkly_api.models.custom_workflow_output import CustomWorkflowOutput
from launchdarkly_api.models.custom_workflow_stage_meta import CustomWorkflowStageMeta
from launchdarkly_api.models.custom_workflows_listing_output import CustomWorkflowsListingOutput
from launchdarkly_api.models.default_client_side_availability import DefaultClientSideAvailability
from launchdarkly_api.models.default_client_side_availability_post import DefaultClientSideAvailabilityPost
from launchdarkly_api.models.defaults import Defaults
from launchdarkly_api.models.dependent_experiment_rep import DependentExperimentRep
from launchdarkly_api.models.dependent_flag import DependentFlag
from launchdarkly_api.models.dependent_flag_environment import DependentFlagEnvironment
from launchdarkly_api.models.dependent_flags_by_environment import DependentFlagsByEnvironment
from launchdarkly_api.models.dependent_measured_rollout_rep import DependentMeasuredRolloutRep
from launchdarkly_api.models.dependent_metric_group_rep import DependentMetricGroupRep
from launchdarkly_api.models.dependent_metric_group_rep_with_metrics import DependentMetricGroupRepWithMetrics
from launchdarkly_api.models.dependent_metric_or_metric_group_rep import DependentMetricOrMetricGroupRep
from launchdarkly_api.models.deployment_collection_rep import DeploymentCollectionRep
from launchdarkly_api.models.deployment_rep import DeploymentRep
from launchdarkly_api.models.destination import Destination
from launchdarkly_api.models.destination_post import DestinationPost
from launchdarkly_api.models.destinations import Destinations
from launchdarkly_api.models.dynamic_options import DynamicOptions
from launchdarkly_api.models.dynamic_options_parser import DynamicOptionsParser
from launchdarkly_api.models.endpoint import Endpoint
from launchdarkly_api.models.environment import Environment
from launchdarkly_api.models.environment_post import EnvironmentPost
from launchdarkly_api.models.environment_summary import EnvironmentSummary
from launchdarkly_api.models.environments import Environments
from launchdarkly_api.models.error import Error
from launchdarkly_api.models.evaluation_reason import EvaluationReason
from launchdarkly_api.models.evaluations_summary import EvaluationsSummary
from launchdarkly_api.models.event_filter import EventFilter
from launchdarkly_api.models.execution_output import ExecutionOutput
from launchdarkly_api.models.expandable_approval_request_response import ExpandableApprovalRequestResponse
from launchdarkly_api.models.expandable_approval_requests_response import ExpandableApprovalRequestsResponse
from launchdarkly_api.models.expanded_ai_config import ExpandedAIConfig
from launchdarkly_api.models.expanded_directly_linked_flag import ExpandedDirectlyLinkedFlag
from launchdarkly_api.models.expanded_directly_linked_flags import ExpandedDirectlyLinkedFlags
from launchdarkly_api.models.expanded_directly_linked_segment import ExpandedDirectlyLinkedSegment
from launchdarkly_api.models.expanded_directly_linked_segments import ExpandedDirectlyLinkedSegments
from launchdarkly_api.models.expanded_flag import ExpandedFlag
from launchdarkly_api.models.expanded_flag_rep import ExpandedFlagRep
from launchdarkly_api.models.expanded_linked_ai_configs import ExpandedLinkedAIConfigs
from launchdarkly_api.models.expanded_linked_flags import ExpandedLinkedFlags
from launchdarkly_api.models.expanded_linked_metrics import ExpandedLinkedMetrics
from launchdarkly_api.models.expanded_linked_resources import ExpandedLinkedResources
from launchdarkly_api.models.expanded_linked_resources_ai_configs import ExpandedLinkedResourcesAIConfigs
from launchdarkly_api.models.expanded_linked_resources_flags import ExpandedLinkedResourcesFlags
from launchdarkly_api.models.expanded_linked_resources_items import ExpandedLinkedResourcesItems
from launchdarkly_api.models.expanded_linked_resources_metrics import ExpandedLinkedResourcesMetrics
from launchdarkly_api.models.expanded_linked_resources_segments import ExpandedLinkedResourcesSegments
from launchdarkly_api.models.expanded_linked_segments import ExpandedLinkedSegments
from launchdarkly_api.models.expanded_metric import ExpandedMetric
from launchdarkly_api.models.expanded_resource_rep import ExpandedResourceRep
from launchdarkly_api.models.expanded_segment import ExpandedSegment
from launchdarkly_api.models.experiment import Experiment
from launchdarkly_api.models.experiment_allocation_rep import ExperimentAllocationRep
from launchdarkly_api.models.experiment_collection_rep import ExperimentCollectionRep
from launchdarkly_api.models.experiment_enabled_period_rep import ExperimentEnabledPeriodRep
from launchdarkly_api.models.experiment_environment_setting_rep import ExperimentEnvironmentSettingRep
from launchdarkly_api.models.experiment_info_rep import ExperimentInfoRep
from launchdarkly_api.models.experiment_patch_input import ExperimentPatchInput
from launchdarkly_api.models.experiment_post import ExperimentPost
from launchdarkly_api.models.expiring_target import ExpiringTarget
from launchdarkly_api.models.expiring_target_error import ExpiringTargetError
from launchdarkly_api.models.expiring_target_get_response import ExpiringTargetGetResponse
from launchdarkly_api.models.expiring_target_patch_response import ExpiringTargetPatchResponse
from launchdarkly_api.models.expiring_user_target_get_response import ExpiringUserTargetGetResponse
from launchdarkly_api.models.expiring_user_target_item import ExpiringUserTargetItem
from launchdarkly_api.models.expiring_user_target_patch_response import ExpiringUserTargetPatchResponse
from launchdarkly_api.models.export import Export
from launchdarkly_api.models.extinction import Extinction
from launchdarkly_api.models.extinction_collection_rep import ExtinctionCollectionRep
from launchdarkly_api.models.failed_resource_link import FailedResourceLink
from launchdarkly_api.models.failure_reason_rep import FailureReasonRep
from launchdarkly_api.models.feature_flag import FeatureFlag
from launchdarkly_api.models.feature_flag_body import FeatureFlagBody
from launchdarkly_api.models.feature_flag_config import FeatureFlagConfig
from launchdarkly_api.models.feature_flag_scheduled_change import FeatureFlagScheduledChange
from launchdarkly_api.models.feature_flag_scheduled_changes import FeatureFlagScheduledChanges
from launchdarkly_api.models.feature_flag_status import FeatureFlagStatus
from launchdarkly_api.models.feature_flag_status_across_environments import FeatureFlagStatusAcrossEnvironments
from launchdarkly_api.models.feature_flag_statuses import FeatureFlagStatuses
from launchdarkly_api.models.feature_flags import FeatureFlags
from launchdarkly_api.models.file_rep import FileRep
from launchdarkly_api.models.filter import Filter
from launchdarkly_api.models.flag_config_approval_request_response import FlagConfigApprovalRequestResponse
from launchdarkly_api.models.flag_config_approval_requests_response import FlagConfigApprovalRequestsResponse
from launchdarkly_api.models.flag_config_evaluation import FlagConfigEvaluation
from launchdarkly_api.models.flag_config_migration_settings_rep import FlagConfigMigrationSettingsRep
from launchdarkly_api.models.flag_copy_config_environment import FlagCopyConfigEnvironment
from launchdarkly_api.models.flag_copy_config_post import FlagCopyConfigPost
from launchdarkly_api.models.flag_defaults_rep import FlagDefaultsRep
from launchdarkly_api.models.flag_event_collection_rep import FlagEventCollectionRep
from launchdarkly_api.models.flag_event_experiment import FlagEventExperiment
from launchdarkly_api.models.flag_event_experiment_collection import FlagEventExperimentCollection
from launchdarkly_api.models.flag_event_experiment_iteration import FlagEventExperimentIteration
from launchdarkly_api.models.flag_event_impact_rep import FlagEventImpactRep
from launchdarkly_api.models.flag_event_member_rep import FlagEventMemberRep
from launchdarkly_api.models.flag_event_rep import FlagEventRep
from launchdarkly_api.models.flag_followers_by_proj_env_get_rep import FlagFollowersByProjEnvGetRep
from launchdarkly_api.models.flag_followers_get_rep import FlagFollowersGetRep
from launchdarkly_api.models.flag_import_configuration_post import FlagImportConfigurationPost
from launchdarkly_api.models.flag_import_integration import FlagImportIntegration
from launchdarkly_api.models.flag_import_integration_collection import FlagImportIntegrationCollection
from launchdarkly_api.models.flag_import_integration_collection_links import FlagImportIntegrationCollectionLinks
from launchdarkly_api.models.flag_import_integration_links import FlagImportIntegrationLinks
from launchdarkly_api.models.flag_import_status import FlagImportStatus
from launchdarkly_api.models.flag_input import FlagInput
from launchdarkly_api.models.flag_link_collection_rep import FlagLinkCollectionRep
from launchdarkly_api.models.flag_link_member import FlagLinkMember
from launchdarkly_api.models.flag_link_post import FlagLinkPost
from launchdarkly_api.models.flag_link_rep import FlagLinkRep
from launchdarkly_api.models.flag_listing_rep import FlagListingRep
from launchdarkly_api.models.flag_migration_settings_rep import FlagMigrationSettingsRep
from launchdarkly_api.models.flag_prerequisite_post import FlagPrerequisitePost
from launchdarkly_api.models.flag_reference_collection_rep import FlagReferenceCollectionRep
from launchdarkly_api.models.flag_reference_rep import FlagReferenceRep
from launchdarkly_api.models.flag_rep import FlagRep
from launchdarkly_api.models.flag_scheduled_changes_input import FlagScheduledChangesInput
from launchdarkly_api.models.flag_sempatch import FlagSempatch
from launchdarkly_api.models.flag_status_rep import FlagStatusRep
from launchdarkly_api.models.flag_summary import FlagSummary
from launchdarkly_api.models.flag_trigger_input import FlagTriggerInput
from launchdarkly_api.models.flags_summary import FlagsSummary
from launchdarkly_api.models.follow_flag_member import FollowFlagMember
from launchdarkly_api.models.followers_per_flag import FollowersPerFlag
from launchdarkly_api.models.forbidden_error_rep import ForbiddenErrorRep
from launchdarkly_api.models.form_variable import FormVariable
from launchdarkly_api.models.generate_trust_policy_post_rep import GenerateTrustPolicyPostRep
from launchdarkly_api.models.generate_warehouse_destination_key_pair_post_rep import GenerateWarehouseDestinationKeyPairPostRep
from launchdarkly_api.models.get_announcements_public200_response import GetAnnouncementsPublic200Response
from launchdarkly_api.models.guarded_release_config import GuardedReleaseConfig
from launchdarkly_api.models.hmac_signature import HMACSignature
from launchdarkly_api.models.header_items import HeaderItems
from launchdarkly_api.models.holdout_detail_rep import HoldoutDetailRep
from launchdarkly_api.models.holdout_patch_input import HoldoutPatchInput
from launchdarkly_api.models.holdout_post_request import HoldoutPostRequest
from launchdarkly_api.models.holdout_rep import HoldoutRep
from launchdarkly_api.models.holdouts_collection_rep import HoldoutsCollectionRep
from launchdarkly_api.models.hunk_rep import HunkRep
from launchdarkly_api.models.initiator_rep import InitiatorRep
from launchdarkly_api.models.insight_group import InsightGroup
from launchdarkly_api.models.insight_group_collection import InsightGroupCollection
from launchdarkly_api.models.insight_group_collection_metadata import InsightGroupCollectionMetadata
from launchdarkly_api.models.insight_group_collection_score_metadata import InsightGroupCollectionScoreMetadata
from launchdarkly_api.models.insight_group_scores import InsightGroupScores
from launchdarkly_api.models.insight_groups_count_by_indicator import InsightGroupsCountByIndicator
from launchdarkly_api.models.insight_period import InsightPeriod
from launchdarkly_api.models.insight_scores import InsightScores
from launchdarkly_api.models.insights_chart import InsightsChart
from launchdarkly_api.models.insights_chart_bounds import InsightsChartBounds
from launchdarkly_api.models.insights_chart_metadata import InsightsChartMetadata
from launchdarkly_api.models.insights_chart_metric import InsightsChartMetric
from launchdarkly_api.models.insights_chart_series import InsightsChartSeries
from launchdarkly_api.models.insights_chart_series_data_point import InsightsChartSeriesDataPoint
from launchdarkly_api.models.insights_chart_series_metadata import InsightsChartSeriesMetadata
from launchdarkly_api.models.insights_chart_series_metadata_axis import InsightsChartSeriesMetadataAxis
from launchdarkly_api.models.insights_metric_indicator_range import InsightsMetricIndicatorRange
from launchdarkly_api.models.insights_metric_score import InsightsMetricScore
from launchdarkly_api.models.insights_metric_tier_definition import InsightsMetricTierDefinition
from launchdarkly_api.models.insights_repository import InsightsRepository
from launchdarkly_api.models.insights_repository_collection import InsightsRepositoryCollection
from launchdarkly_api.models.insights_repository_project import InsightsRepositoryProject
from launchdarkly_api.models.insights_repository_project_collection import InsightsRepositoryProjectCollection
from launchdarkly_api.models.insights_repository_project_mappings import InsightsRepositoryProjectMappings
from launchdarkly_api.models.instruction_user_request import InstructionUserRequest
from launchdarkly_api.models.integration import Integration
from launchdarkly_api.models.integration_configuration_collection_rep import IntegrationConfigurationCollectionRep
from launchdarkly_api.models.integration_configuration_post import IntegrationConfigurationPost
from launchdarkly_api.models.integration_configurations_rep import IntegrationConfigurationsRep
from launchdarkly_api.models.integration_delivery_configuration import IntegrationDeliveryConfiguration
from launchdarkly_api.models.integration_delivery_configuration_collection import IntegrationDeliveryConfigurationCollection
from launchdarkly_api.models.integration_delivery_configuration_collection_links import IntegrationDeliveryConfigurationCollectionLinks
from launchdarkly_api.models.integration_delivery_configuration_links import IntegrationDeliveryConfigurationLinks
from launchdarkly_api.models.integration_delivery_configuration_post import IntegrationDeliveryConfigurationPost
from launchdarkly_api.models.integration_delivery_configuration_response import IntegrationDeliveryConfigurationResponse
from launchdarkly_api.models.integration_metadata import IntegrationMetadata
from launchdarkly_api.models.integration_status import IntegrationStatus
from launchdarkly_api.models.integration_status_rep import IntegrationStatusRep
from launchdarkly_api.models.integration_subscription_status_rep import IntegrationSubscriptionStatusRep
from launchdarkly_api.models.integrations import Integrations
from launchdarkly_api.models.invalid_request_error_rep import InvalidRequestErrorRep
from launchdarkly_api.models.ip_list import IpList
from launchdarkly_api.models.iteration_input import IterationInput
from launchdarkly_api.models.iteration_rep import IterationRep
from launchdarkly_api.models.judge_attachment import JudgeAttachment
from launchdarkly_api.models.judge_configuration import JudgeConfiguration
from launchdarkly_api.models.last_seen_metadata import LastSeenMetadata
from launchdarkly_api.models.layer_collection_rep import LayerCollectionRep
from launchdarkly_api.models.layer_configuration_rep import LayerConfigurationRep
from launchdarkly_api.models.layer_patch_input import LayerPatchInput
from launchdarkly_api.models.layer_post import LayerPost
from launchdarkly_api.models.layer_rep import LayerRep
from launchdarkly_api.models.layer_reservation_rep import LayerReservationRep
from launchdarkly_api.models.layer_snapshot_rep import LayerSnapshotRep
from launchdarkly_api.models.lead_time_stages_rep import LeadTimeStagesRep
from launchdarkly_api.models.legacy_experiment_rep import LegacyExperimentRep
from launchdarkly_api.models.link import Link
from launchdarkly_api.models.link_resource_success_response import LinkResourceSuccessResponse
from launchdarkly_api.models.maintainer import Maintainer
from launchdarkly_api.models.maintainer_member import MaintainerMember
from launchdarkly_api.models.maintainer_rep import MaintainerRep
from launchdarkly_api.models.maintainer_team import MaintainerTeam
from launchdarkly_api.models.member import Member
from launchdarkly_api.models.member_data_rep import MemberDataRep
from launchdarkly_api.models.member_import_item import MemberImportItem
from launchdarkly_api.models.member_permission_grant_summary_rep import MemberPermissionGrantSummaryRep
from launchdarkly_api.models.member_summary import MemberSummary
from launchdarkly_api.models.member_team_summary_rep import MemberTeamSummaryRep
from launchdarkly_api.models.member_teams_post_input import MemberTeamsPostInput
from launchdarkly_api.models.members import Members
from launchdarkly_api.models.members_patch_input import MembersPatchInput
from launchdarkly_api.models.message import Message
from launchdarkly_api.models.method_not_allowed_error_rep import MethodNotAllowedErrorRep
from launchdarkly_api.models.metric_by_variation import MetricByVariation
from launchdarkly_api.models.metric_collection_rep import MetricCollectionRep
from launchdarkly_api.models.metric_data_source_ref_rep import MetricDataSourceRefRep
from launchdarkly_api.models.metric_event_default_rep import MetricEventDefaultRep
from launchdarkly_api.models.metric_group_collection_rep import MetricGroupCollectionRep
from launchdarkly_api.models.metric_group_post import MetricGroupPost
from launchdarkly_api.models.metric_group_rep import MetricGroupRep
from launchdarkly_api.models.metric_in_group_rep import MetricInGroupRep
from launchdarkly_api.models.metric_in_metric_group_input import MetricInMetricGroupInput
from launchdarkly_api.models.metric_input import MetricInput
from launchdarkly_api.models.metric_listing_rep import MetricListingRep
from launchdarkly_api.models.metric_post import MetricPost
from launchdarkly_api.models.metric_rep import MetricRep
from launchdarkly_api.models.metric_v2_rep import MetricV2Rep
from launchdarkly_api.models.metrics import Metrics
from launchdarkly_api.models.metrics_summary import MetricsSummary
from launchdarkly_api.models.migration_safety_issue_rep import MigrationSafetyIssueRep
from launchdarkly_api.models.migration_settings_post import MigrationSettingsPost
from launchdarkly_api.models.model_config import ModelConfig
from launchdarkly_api.models.model_config_post import ModelConfigPost
from launchdarkly_api.models.model_import import ModelImport
from launchdarkly_api.models.modification import Modification
from launchdarkly_api.models.multi_environment_dependent_flag import MultiEnvironmentDependentFlag
from launchdarkly_api.models.multi_environment_dependent_flags import MultiEnvironmentDependentFlags
from launchdarkly_api.models.naming_convention import NamingConvention
from launchdarkly_api.models.new_member_form import NewMemberForm
from launchdarkly_api.models.not_found_error_rep import NotFoundErrorRep
from launchdarkly_api.models.oauth_client_post import OauthClientPost
from launchdarkly_api.models.options_array import OptionsArray
from launchdarkly_api.models.paginated_links import PaginatedLinks
from launchdarkly_api.models.parameter_default import ParameterDefault
from launchdarkly_api.models.parameter_rep import ParameterRep
from launchdarkly_api.models.parent_and_self_links import ParentAndSelfLinks
from launchdarkly_api.models.parent_link import ParentLink
from launchdarkly_api.models.parent_resource_rep import ParentResourceRep
from launchdarkly_api.models.patch_failed_error_rep import PatchFailedErrorRep
from launchdarkly_api.models.patch_flags_request import PatchFlagsRequest
from launchdarkly_api.models.patch_operation import PatchOperation
from launchdarkly_api.models.patch_segment_expiring_target_input_rep import PatchSegmentExpiringTargetInputRep
from launchdarkly_api.models.patch_segment_expiring_target_instruction import PatchSegmentExpiringTargetInstruction
from launchdarkly_api.models.patch_segment_instruction import PatchSegmentInstruction
from launchdarkly_api.models.patch_segment_request import PatchSegmentRequest
from launchdarkly_api.models.patch_users_request import PatchUsersRequest
from launchdarkly_api.models.patch_with_comment import PatchWithComment
from launchdarkly_api.models.permission_grant_input import PermissionGrantInput
from launchdarkly_api.models.phase import Phase
from launchdarkly_api.models.phase_info import PhaseInfo
from launchdarkly_api.models.post_approval_request_apply_request import PostApprovalRequestApplyRequest
from launchdarkly_api.models.post_approval_request_review_request import PostApprovalRequestReviewRequest
from launchdarkly_api.models.post_deployment_event_input import PostDeploymentEventInput
from launchdarkly_api.models.post_flag_scheduled_changes_input import PostFlagScheduledChangesInput
from launchdarkly_api.models.post_insight_group_params import PostInsightGroupParams
from launchdarkly_api.models.post_release_policy_request import PostReleasePolicyRequest
from launchdarkly_api.models.prerequisite import Prerequisite
from launchdarkly_api.models.progressive_release_config import ProgressiveReleaseConfig
from launchdarkly_api.models.project import Project
from launchdarkly_api.models.project_post import ProjectPost
from launchdarkly_api.models.project_rep import ProjectRep
from launchdarkly_api.models.project_summary import ProjectSummary
from launchdarkly_api.models.project_summary_collection import ProjectSummaryCollection
from launchdarkly_api.models.projects import Projects
from launchdarkly_api.models.pull_request_collection_rep import PullRequestCollectionRep
from launchdarkly_api.models.pull_request_lead_time_rep import PullRequestLeadTimeRep
from launchdarkly_api.models.pull_request_rep import PullRequestRep
from launchdarkly_api.models.put_branch import PutBranch
from launchdarkly_api.models.put_release_policy_request import PutReleasePolicyRequest
from launchdarkly_api.models.randomization_settings_put import RandomizationSettingsPut
from launchdarkly_api.models.randomization_settings_rep import RandomizationSettingsRep
from launchdarkly_api.models.randomization_unit_input import RandomizationUnitInput
from launchdarkly_api.models.randomization_unit_rep import RandomizationUnitRep
from launchdarkly_api.models.rate_limited_error_rep import RateLimitedErrorRep
from launchdarkly_api.models.recent_trigger_body import RecentTriggerBody
from launchdarkly_api.models.reference_rep import ReferenceRep
from launchdarkly_api.models.related_experiment_rep import RelatedExperimentRep
from launchdarkly_api.models.relay_auto_config_collection_rep import RelayAutoConfigCollectionRep
from launchdarkly_api.models.relay_auto_config_post import RelayAutoConfigPost
from launchdarkly_api.models.relay_auto_config_rep import RelayAutoConfigRep
from launchdarkly_api.models.release import Release
from launchdarkly_api.models.release_audience import ReleaseAudience
from launchdarkly_api.models.release_guardian_configuration import ReleaseGuardianConfiguration
from launchdarkly_api.models.release_guardian_configuration_input import ReleaseGuardianConfigurationInput
from launchdarkly_api.models.release_method import ReleaseMethod
from launchdarkly_api.models.release_phase import ReleasePhase
from launchdarkly_api.models.release_pipeline import ReleasePipeline
from launchdarkly_api.models.release_pipeline_collection import ReleasePipelineCollection
from launchdarkly_api.models.release_policies_access import ReleasePoliciesAccess
from launchdarkly_api.models.release_policies_access_allowed_reason import ReleasePoliciesAccessAllowedReason
from launchdarkly_api.models.release_policies_access_allowed_rep import ReleasePoliciesAccessAllowedRep
from launchdarkly_api.models.release_policies_access_denied import ReleasePoliciesAccessDenied
from launchdarkly_api.models.release_policies_access_denied_reason import ReleasePoliciesAccessDeniedReason
from launchdarkly_api.models.release_policies_access_rep import ReleasePoliciesAccessRep
from launchdarkly_api.models.release_policies_response import ReleasePoliciesResponse
from launchdarkly_api.models.release_policy import ReleasePolicy
from launchdarkly_api.models.release_policy_scope import ReleasePolicyScope
from launchdarkly_api.models.release_policy_stage import ReleasePolicyStage
from launchdarkly_api.models.release_progression import ReleaseProgression
from launchdarkly_api.models.release_progression_collection import ReleaseProgressionCollection
from launchdarkly_api.models.releaser_audience_config_input import ReleaserAudienceConfigInput
from launchdarkly_api.models.repository_collection_rep import RepositoryCollectionRep
from launchdarkly_api.models.repository_post import RepositoryPost
from launchdarkly_api.models.repository_rep import RepositoryRep
from launchdarkly_api.models.resource_access import ResourceAccess
from launchdarkly_api.models.resource_id_response import ResourceIDResponse
from launchdarkly_api.models.resource_id import ResourceId
from launchdarkly_api.models.resource_summary import ResourceSummary
from launchdarkly_api.models.restricted_model_error import RestrictedModelError
from launchdarkly_api.models.restricted_models_request import RestrictedModelsRequest
from launchdarkly_api.models.restricted_models_response import RestrictedModelsResponse
from launchdarkly_api.models.review_output import ReviewOutput
from launchdarkly_api.models.review_response import ReviewResponse
from launchdarkly_api.models.rollout import Rollout
from launchdarkly_api.models.root_response import RootResponse
from launchdarkly_api.models.rule import Rule
from launchdarkly_api.models.rule_clause import RuleClause
from launchdarkly_api.models.sdk_list_rep import SdkListRep
from launchdarkly_api.models.sdk_version_list_rep import SdkVersionListRep
from launchdarkly_api.models.sdk_version_rep import SdkVersionRep
from launchdarkly_api.models.segment_body import SegmentBody
from launchdarkly_api.models.segment_metadata import SegmentMetadata
from launchdarkly_api.models.segment_target import SegmentTarget
from launchdarkly_api.models.segment_user_list import SegmentUserList
from launchdarkly_api.models.segment_user_state import SegmentUserState
from launchdarkly_api.models.segments_summary import SegmentsSummary
from launchdarkly_api.models.series_list_rep import SeriesListRep
from launchdarkly_api.models.series_list_rep_float import SeriesListRepFloat
from launchdarkly_api.models.simple_holdout_rep import SimpleHoldoutRep
from launchdarkly_api.models.source_env import SourceEnv
from launchdarkly_api.models.source_flag import SourceFlag
from launchdarkly_api.models.stage_input import StageInput
from launchdarkly_api.models.stage_output import StageOutput
from launchdarkly_api.models.statement import Statement
from launchdarkly_api.models.statement_post import StatementPost
from launchdarkly_api.models.statistic_collection_rep import StatisticCollectionRep
from launchdarkly_api.models.statistic_rep import StatisticRep
from launchdarkly_api.models.statistics_root import StatisticsRoot
from launchdarkly_api.models.status_conflict_error_rep import StatusConflictErrorRep
from launchdarkly_api.models.status_response import StatusResponse
from launchdarkly_api.models.status_service_unavailable import StatusServiceUnavailable
from launchdarkly_api.models.store_integration_error import StoreIntegrationError
from launchdarkly_api.models.subject_data_rep import SubjectDataRep
from launchdarkly_api.models.subscription_post import SubscriptionPost
from launchdarkly_api.models.tags_collection import TagsCollection
from launchdarkly_api.models.tags_link import TagsLink
from launchdarkly_api.models.target import Target
from launchdarkly_api.models.target_resource_rep import TargetResourceRep
from launchdarkly_api.models.team import Team
from launchdarkly_api.models.team_custom_role import TeamCustomRole
from launchdarkly_api.models.team_custom_roles import TeamCustomRoles
from launchdarkly_api.models.team_imports_rep import TeamImportsRep
from launchdarkly_api.models.team_maintainers import TeamMaintainers
from launchdarkly_api.models.team_members import TeamMembers
from launchdarkly_api.models.team_patch_input import TeamPatchInput
from launchdarkly_api.models.team_post_input import TeamPostInput
from launchdarkly_api.models.team_projects import TeamProjects
from launchdarkly_api.models.teams import Teams
from launchdarkly_api.models.teams_patch_input import TeamsPatchInput
from launchdarkly_api.models.timestamp_rep import TimestampRep
from launchdarkly_api.models.token import Token
from launchdarkly_api.models.token_summary import TokenSummary
from launchdarkly_api.models.tokens import Tokens
from launchdarkly_api.models.treatment_input import TreatmentInput
from launchdarkly_api.models.treatment_parameter_input import TreatmentParameterInput
from launchdarkly_api.models.treatment_rep import TreatmentRep
from launchdarkly_api.models.trigger_post import TriggerPost
from launchdarkly_api.models.trigger_workflow_collection_rep import TriggerWorkflowCollectionRep
from launchdarkly_api.models.trigger_workflow_rep import TriggerWorkflowRep
from launchdarkly_api.models.trust_policy_details import TrustPolicyDetails
from launchdarkly_api.models.trust_policy_statement import TrustPolicyStatement
from launchdarkly_api.models.unauthorized_error_rep import UnauthorizedErrorRep
from launchdarkly_api.models.unlink_resource_success_response import UnlinkResourceSuccessResponse
from launchdarkly_api.models.update_phase_status_input import UpdatePhaseStatusInput
from launchdarkly_api.models.update_release_pipeline_input import UpdateReleasePipelineInput
from launchdarkly_api.models.upsert_context_kind_payload import UpsertContextKindPayload
from launchdarkly_api.models.upsert_flag_defaults_payload import UpsertFlagDefaultsPayload
from launchdarkly_api.models.upsert_payload_rep import UpsertPayloadRep
from launchdarkly_api.models.upsert_response_rep import UpsertResponseRep
from launchdarkly_api.models.url_post import UrlPost
from launchdarkly_api.models.user import User
from launchdarkly_api.models.user_attribute_names_rep import UserAttributeNamesRep
from launchdarkly_api.models.user_flag_setting import UserFlagSetting
from launchdarkly_api.models.user_flag_settings import UserFlagSettings
from launchdarkly_api.models.user_record import UserRecord
from launchdarkly_api.models.user_segment import UserSegment
from launchdarkly_api.models.user_segment_rule import UserSegmentRule
from launchdarkly_api.models.user_segments import UserSegments
from launchdarkly_api.models.users import Users
from launchdarkly_api.models.users_rep import UsersRep
from launchdarkly_api.models.validation_failed_error_rep import ValidationFailedErrorRep
from launchdarkly_api.models.value_put import ValuePut
from launchdarkly_api.models.variation import Variation
from launchdarkly_api.models.variation_eval_summary import VariationEvalSummary
from launchdarkly_api.models.variation_or_rollout_rep import VariationOrRolloutRep
from launchdarkly_api.models.variation_summary import VariationSummary
from launchdarkly_api.models.variation_tool import VariationTool
from launchdarkly_api.models.variation_tool_post import VariationToolPost
from launchdarkly_api.models.versions_rep import VersionsRep
from launchdarkly_api.models.view import View
from launchdarkly_api.models.view_link_request import ViewLinkRequest
from launchdarkly_api.models.view_link_request_keys import ViewLinkRequestKeys
from launchdarkly_api.models.view_link_request_segment_identifier import ViewLinkRequestSegmentIdentifier
from launchdarkly_api.models.view_link_request_segment_identifiers import ViewLinkRequestSegmentIdentifiers
from launchdarkly_api.models.view_linked_resource import ViewLinkedResource
from launchdarkly_api.models.view_linked_resource_details import ViewLinkedResourceDetails
from launchdarkly_api.models.view_linked_resources import ViewLinkedResources
from launchdarkly_api.models.view_patch import ViewPatch
from launchdarkly_api.models.view_post import ViewPost
from launchdarkly_api.models.views import Views
from launchdarkly_api.models.views_access import ViewsAccess
from launchdarkly_api.models.views_access_allowed_reason import ViewsAccessAllowedReason
from launchdarkly_api.models.views_access_allowed_rep import ViewsAccessAllowedRep
from launchdarkly_api.models.views_access_denied import ViewsAccessDenied
from launchdarkly_api.models.views_access_denied_reason import ViewsAccessDeniedReason
from launchdarkly_api.models.views_access_rep import ViewsAccessRep
from launchdarkly_api.models.views_link import ViewsLink
from launchdarkly_api.models.views_maintainer_member import ViewsMaintainerMember
from launchdarkly_api.models.views_maintainer_team import ViewsMaintainerTeam
from launchdarkly_api.models.views_paginated_links import ViewsPaginatedLinks
from launchdarkly_api.models.views_self_link import ViewsSelfLink
from launchdarkly_api.models.webhook import Webhook
from launchdarkly_api.models.webhook_post import WebhookPost
from launchdarkly_api.models.webhooks import Webhooks
from launchdarkly_api.models.weighted_variation import WeightedVariation
from launchdarkly_api.models.workflow_template_metadata import WorkflowTemplateMetadata
from launchdarkly_api.models.workflow_template_output import WorkflowTemplateOutput
from launchdarkly_api.models.workflow_template_parameter import WorkflowTemplateParameter
from launchdarkly_api.models.workflow_templates_listing_output_rep import WorkflowTemplatesListingOutputRep

