# coding: utf-8

"""
    LaunchDarkly REST API

    Build custom integrations with the LaunchDarkly REST API  # noqa: E501

    OpenAPI spec version: 5.0.1
    Contact: support@launchdarkly.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from launchdarkly_api.models.hierarchical_links import HierarchicalLinks  # noqa: F401,E501
from launchdarkly_api.models.id import Id  # noqa: F401,E501
from launchdarkly_api.models.integration_subscription_status import IntegrationSubscriptionStatus  # noqa: F401,E501
from launchdarkly_api.models.statement import Statement  # noqa: F401,E501


class IntegrationSubscription(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'links': 'HierarchicalLinks',
        'id': 'Id',
        'kind': 'str',
        'name': 'str',
        'config': 'object',
        'statements': 'list[Statement]',
        'on': 'bool',
        'tags': 'list[str]',
        'status': 'IntegrationSubscriptionStatus'
    }

    attribute_map = {
        'links': '_links',
        'id': '_id',
        'kind': 'kind',
        'name': 'name',
        'config': 'config',
        'statements': 'statements',
        'on': 'on',
        'tags': 'tags',
        'status': '_status'
    }

    def __init__(self, links=None, id=None, kind=None, name=None, config=None, statements=None, on=None, tags=None, status=None):  # noqa: E501
        """IntegrationSubscription - a model defined in Swagger"""  # noqa: E501

        self._links = None
        self._id = None
        self._kind = None
        self._name = None
        self._config = None
        self._statements = None
        self._on = None
        self._tags = None
        self._status = None
        self.discriminator = None

        if links is not None:
            self.links = links
        if id is not None:
            self.id = id
        if kind is not None:
            self.kind = kind
        if name is not None:
            self.name = name
        if config is not None:
            self.config = config
        if statements is not None:
            self.statements = statements
        if on is not None:
            self.on = on
        if tags is not None:
            self.tags = tags
        if status is not None:
            self.status = status

    @property
    def links(self):
        """Gets the links of this IntegrationSubscription.  # noqa: E501


        :return: The links of this IntegrationSubscription.  # noqa: E501
        :rtype: HierarchicalLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this IntegrationSubscription.


        :param links: The links of this IntegrationSubscription.  # noqa: E501
        :type: HierarchicalLinks
        """

        self._links = links

    @property
    def id(self):
        """Gets the id of this IntegrationSubscription.  # noqa: E501


        :return: The id of this IntegrationSubscription.  # noqa: E501
        :rtype: Id
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this IntegrationSubscription.


        :param id: The id of this IntegrationSubscription.  # noqa: E501
        :type: Id
        """

        self._id = id

    @property
    def kind(self):
        """Gets the kind of this IntegrationSubscription.  # noqa: E501

        The type of integration associated with this configuration.  # noqa: E501

        :return: The kind of this IntegrationSubscription.  # noqa: E501
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this IntegrationSubscription.

        The type of integration associated with this configuration.  # noqa: E501

        :param kind: The kind of this IntegrationSubscription.  # noqa: E501
        :type: str
        """

        self._kind = kind

    @property
    def name(self):
        """Gets the name of this IntegrationSubscription.  # noqa: E501

        The user-defined name associated with this configuration.  # noqa: E501

        :return: The name of this IntegrationSubscription.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this IntegrationSubscription.

        The user-defined name associated with this configuration.  # noqa: E501

        :param name: The name of this IntegrationSubscription.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def config(self):
        """Gets the config of this IntegrationSubscription.  # noqa: E501

        A key-value mapping of configuration fields.  # noqa: E501

        :return: The config of this IntegrationSubscription.  # noqa: E501
        :rtype: object
        """
        return self._config

    @config.setter
    def config(self, config):
        """Sets the config of this IntegrationSubscription.

        A key-value mapping of configuration fields.  # noqa: E501

        :param config: The config of this IntegrationSubscription.  # noqa: E501
        :type: object
        """

        self._config = config

    @property
    def statements(self):
        """Gets the statements of this IntegrationSubscription.  # noqa: E501


        :return: The statements of this IntegrationSubscription.  # noqa: E501
        :rtype: list[Statement]
        """
        return self._statements

    @statements.setter
    def statements(self, statements):
        """Sets the statements of this IntegrationSubscription.


        :param statements: The statements of this IntegrationSubscription.  # noqa: E501
        :type: list[Statement]
        """

        self._statements = statements

    @property
    def on(self):
        """Gets the on of this IntegrationSubscription.  # noqa: E501

        Whether or not the integration is currently active.  # noqa: E501

        :return: The on of this IntegrationSubscription.  # noqa: E501
        :rtype: bool
        """
        return self._on

    @on.setter
    def on(self, on):
        """Sets the on of this IntegrationSubscription.

        Whether or not the integration is currently active.  # noqa: E501

        :param on: The on of this IntegrationSubscription.  # noqa: E501
        :type: bool
        """

        self._on = on

    @property
    def tags(self):
        """Gets the tags of this IntegrationSubscription.  # noqa: E501

        An array of tags for this integration configuration.  # noqa: E501

        :return: The tags of this IntegrationSubscription.  # noqa: E501
        :rtype: list[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this IntegrationSubscription.

        An array of tags for this integration configuration.  # noqa: E501

        :param tags: The tags of this IntegrationSubscription.  # noqa: E501
        :type: list[str]
        """

        self._tags = tags

    @property
    def status(self):
        """Gets the status of this IntegrationSubscription.  # noqa: E501


        :return: The status of this IntegrationSubscription.  # noqa: E501
        :rtype: IntegrationSubscriptionStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this IntegrationSubscription.


        :param status: The status of this IntegrationSubscription.  # noqa: E501
        :type: IntegrationSubscriptionStatus
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IntegrationSubscription, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IntegrationSubscription):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
