# coding: utf-8

"""
    LaunchDarkly REST API

    Build custom integrations with the LaunchDarkly REST API  # noqa: E501

    OpenAPI spec version: 5.0.1
    Contact: support@launchdarkly.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class IntegrationSubscriptionStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'success_count': 'int',
        'last_success': 'int',
        'error_count': 'int'
    }

    attribute_map = {
        'success_count': 'successCount',
        'last_success': 'lastSuccess',
        'error_count': 'errorCount'
    }

    def __init__(self, success_count=None, last_success=None, error_count=None):  # noqa: E501
        """IntegrationSubscriptionStatus - a model defined in Swagger"""  # noqa: E501

        self._success_count = None
        self._last_success = None
        self._error_count = None
        self.discriminator = None

        if success_count is not None:
            self.success_count = success_count
        if last_success is not None:
            self.last_success = last_success
        if error_count is not None:
            self.error_count = error_count

    @property
    def success_count(self):
        """Gets the success_count of this IntegrationSubscriptionStatus.  # noqa: E501


        :return: The success_count of this IntegrationSubscriptionStatus.  # noqa: E501
        :rtype: int
        """
        return self._success_count

    @success_count.setter
    def success_count(self, success_count):
        """Sets the success_count of this IntegrationSubscriptionStatus.


        :param success_count: The success_count of this IntegrationSubscriptionStatus.  # noqa: E501
        :type: int
        """

        self._success_count = success_count

    @property
    def last_success(self):
        """Gets the last_success of this IntegrationSubscriptionStatus.  # noqa: E501

        A unix epoch time in milliseconds specifying the last time this integration was successfully used.  # noqa: E501

        :return: The last_success of this IntegrationSubscriptionStatus.  # noqa: E501
        :rtype: int
        """
        return self._last_success

    @last_success.setter
    def last_success(self, last_success):
        """Sets the last_success of this IntegrationSubscriptionStatus.

        A unix epoch time in milliseconds specifying the last time this integration was successfully used.  # noqa: E501

        :param last_success: The last_success of this IntegrationSubscriptionStatus.  # noqa: E501
        :type: int
        """

        self._last_success = last_success

    @property
    def error_count(self):
        """Gets the error_count of this IntegrationSubscriptionStatus.  # noqa: E501


        :return: The error_count of this IntegrationSubscriptionStatus.  # noqa: E501
        :rtype: int
        """
        return self._error_count

    @error_count.setter
    def error_count(self, error_count):
        """Sets the error_count of this IntegrationSubscriptionStatus.


        :param error_count: The error_count of this IntegrationSubscriptionStatus.  # noqa: E501
        :type: int
        """

        self._error_count = error_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IntegrationSubscriptionStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IntegrationSubscriptionStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
