# coding: utf-8

"""
    LaunchDarkly REST API

    Build custom integrations with the LaunchDarkly REST API

    OpenAPI spec version: 2.0.0
    Contact: support@launchdarkly.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.user_settings_api import UserSettingsApi


class TestUserSettingsApi(unittest.TestCase):
    """ UserSettingsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.user_settings_api.UserSettingsApi()

    def tearDown(self):
        pass

    def test_get_user_flag_setting(self):
        """
        Test case for get_user_flag_setting

        Get a user by key.
        """
        pass

    def test_get_user_flag_settings(self):
        """
        Test case for get_user_flag_settings

        Fetch a single flag setting for a user by key.
        """
        pass

    def test_put_flag_setting(self):
        """
        Test case for put_flag_setting

        Specifically enable or disable a feature flag for a user based on their key.
        """
        pass


if __name__ == '__main__':
    unittest.main()
