# coding: utf-8

"""
    LaunchDarkly REST API

    Build custom integrations with the LaunchDarkly REST API  # noqa: E501

    OpenAPI spec version: 5.0.1
    Contact: support@launchdarkly.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import launchdarkly_api
from launchdarkly_api.models.user_targeting_expiration_resource_id_for_flag import UserTargetingExpirationResourceIdForFlag  # noqa: E501
from launchdarkly_api.rest import ApiException


class TestUserTargetingExpirationResourceIdForFlag(unittest.TestCase):
    """UserTargetingExpirationResourceIdForFlag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserTargetingExpirationResourceIdForFlag(self):
        """Test UserTargetingExpirationResourceIdForFlag"""
        # FIXME: construct object with mandatory attributes with example values
        # model = launchdarkly_api.models.user_targeting_expiration_resource_id_for_flag.UserTargetingExpirationResourceIdForFlag()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
