# coding: utf-8

"""
    LaunchDarkly REST API

    Build custom integrations with the LaunchDarkly REST API

    OpenAPI spec version: 2.0.0
    Contact: support@launchdarkly.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.webhooks_api import WebhooksApi


class TestWebhooksApi(unittest.TestCase):
    """ WebhooksApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.webhooks_api.WebhooksApi()

    def tearDown(self):
        pass

    def test_delete_webhook(self):
        """
        Test case for delete_webhook

        Delete a webhook by ID
        """
        pass

    def test_get_webhook(self):
        """
        Test case for get_webhook

        Get a webhook by ID
        """
        pass

    def test_get_webhooks(self):
        """
        Test case for get_webhooks

        Fetch a list of all webhooks
        """
        pass

    def test_patch_webhook(self):
        """
        Test case for patch_webhook

        Modify a webhook by ID
        """
        pass

    def test_post_webhook(self):
        """
        Test case for post_webhook

        Create a webhook
        """
        pass


if __name__ == '__main__':
    unittest.main()
