# coding: utf-8

"""
    LaunchDarkly REST API

    Build custom integrations with the LaunchDarkly REST API  # noqa: E501

    OpenAPI spec version: 2.0.1
    Contact: support@launchdarkly.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ldapi
from ldapi.models.policy import Policy  # noqa: E501
from ldapi.rest import ApiException


class TestPolicy(unittest.TestCase):
    """Policy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPolicy(self):
        """Test Policy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ldapi.models.policy.Policy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
