# coding: utf-8

"""
    LaunchDarkly REST API

    Build custom integrations with the LaunchDarkly REST API  # noqa: E501

    OpenAPI spec version: 5.0.0
    Contact: support@launchdarkly.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import launchdarkly_api
from launchdarkly_api.api.user_record_api import UserRecordApi  # noqa: E501
from launchdarkly_api.rest import ApiException


class TestUserRecordApi(unittest.TestCase):
    """UserRecordApi unit test stubs"""

    def setUp(self):
        self.api = launchdarkly_api.api.user_record_api.UserRecordApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_user(self):
        """Test case for get_user

        Get a user by key.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
