# coding: utf-8

"""
    LaunchDarkly REST API

    Build custom integrations with the LaunchDarkly REST API  # noqa: E501

    OpenAPI spec version: 5.0.1
    Contact: support@launchdarkly.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import launchdarkly_api
from launchdarkly_api.models.approval_request_config_body import ApprovalRequestConfigBody  # noqa: E501
from launchdarkly_api.rest import ApiException


class TestApprovalRequestConfigBody(unittest.TestCase):
    """ApprovalRequestConfigBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApprovalRequestConfigBody(self):
        """Test ApprovalRequestConfigBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = launchdarkly_api.models.approval_request_config_body.ApprovalRequestConfigBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
