# coding: utf-8

"""
    LaunchDarkly REST API

    Build custom integrations with the LaunchDarkly REST API

    OpenAPI spec version: 2.0.0
    Contact: support@launchdarkly.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.rule import Rule


class TestRule(unittest.TestCase):
    """ Rule unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRule(self):
        """
        Test Rule
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.rule.Rule()
        pass


if __name__ == '__main__':
    unittest.main()
