# coding: utf-8

"""
    LaunchDarkly REST API

    Build custom integrations with the LaunchDarkly REST API

    OpenAPI spec version: 2.0.0
    Contact: support@launchdarkly.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.feature_flag_config_fallthrough import FeatureFlagConfigFallthrough


class TestFeatureFlagConfigFallthrough(unittest.TestCase):
    """ FeatureFlagConfigFallthrough unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFeatureFlagConfigFallthrough(self):
        """
        Test FeatureFlagConfigFallthrough
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.feature_flag_config_fallthrough.FeatureFlagConfigFallthrough()
        pass


if __name__ == '__main__':
    unittest.main()
