# coding: utf-8

"""
    LaunchDarkly REST API

    Build custom integrations with the LaunchDarkly REST API  # noqa: E501

    OpenAPI spec version: 4.0.0
    Contact: support@launchdarkly.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import launchdarkly_api
from launchdarkly_api.models.feature_flag_approval_requests import FeatureFlagApprovalRequests  # noqa: E501
from launchdarkly_api.rest import ApiException


class TestFeatureFlagApprovalRequests(unittest.TestCase):
    """FeatureFlagApprovalRequests unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFeatureFlagApprovalRequests(self):
        """Test FeatureFlagApprovalRequests"""
        # FIXME: construct object with mandatory attributes with example values
        # model = launchdarkly_api.models.feature_flag_approval_requests.FeatureFlagApprovalRequests()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
