# coding: utf-8

"""
    LaunchDarkly REST API

    Build custom integrations with the LaunchDarkly REST API

    OpenAPI spec version: 2.0.0
    Contact: support@launchdarkly.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import sys
import os
import re

# python 2 and python 3 compatibility library
from six import iteritems

from ..configuration import Configuration
from ..api_client import ApiClient


class EnvironmentsApi(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        config = Configuration()
        if api_client:
            self.api_client = api_client
        else:
            if not config.api_client:
                config.api_client = ApiClient()
            self.api_client = config.api_client

    def delete_environment(self, project_key, environment_key, **kwargs):
        """
        Delete an environment by ID
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.delete_environment(project_key, environment_key, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str project_key: The project key, used to tie the flags together under one project so they can be managed together. (required)
        :param str environment_key: The environment key (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.delete_environment_with_http_info(project_key, environment_key, **kwargs)
        else:
            (data) = self.delete_environment_with_http_info(project_key, environment_key, **kwargs)
            return data

    def delete_environment_with_http_info(self, project_key, environment_key, **kwargs):
        """
        Delete an environment by ID
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.delete_environment_with_http_info(project_key, environment_key, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str project_key: The project key, used to tie the flags together under one project so they can be managed together. (required)
        :param str environment_key: The environment key (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['project_key', 'environment_key']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_environment" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'project_key' is set
        if ('project_key' not in params) or (params['project_key'] is None):
            raise ValueError("Missing the required parameter `project_key` when calling `delete_environment`")
        # verify the required parameter 'environment_key' is set
        if ('environment_key' not in params) or (params['environment_key'] is None):
            raise ValueError("Missing the required parameter `environment_key` when calling `delete_environment`")


        collection_formats = {}

        path_params = {}
        if 'project_key' in params:
            path_params['projectKey'] = params['project_key']
        if 'environment_key' in params:
            path_params['environmentKey'] = params['environment_key']

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['Token']

        return self.api_client.call_api('/environments/{projectKey}/{environmentKey}', 'DELETE',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type=None,
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def get_environment(self, project_key, environment_key, **kwargs):
        """
        Get an environment by key.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_environment(project_key, environment_key, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str project_key: The project key, used to tie the flags together under one project so they can be managed together. (required)
        :param str environment_key: The environment key (required)
        :return: Environment
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.get_environment_with_http_info(project_key, environment_key, **kwargs)
        else:
            (data) = self.get_environment_with_http_info(project_key, environment_key, **kwargs)
            return data

    def get_environment_with_http_info(self, project_key, environment_key, **kwargs):
        """
        Get an environment by key.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_environment_with_http_info(project_key, environment_key, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str project_key: The project key, used to tie the flags together under one project so they can be managed together. (required)
        :param str environment_key: The environment key (required)
        :return: Environment
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['project_key', 'environment_key']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_environment" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'project_key' is set
        if ('project_key' not in params) or (params['project_key'] is None):
            raise ValueError("Missing the required parameter `project_key` when calling `get_environment`")
        # verify the required parameter 'environment_key' is set
        if ('environment_key' not in params) or (params['environment_key'] is None):
            raise ValueError("Missing the required parameter `environment_key` when calling `get_environment`")


        collection_formats = {}

        path_params = {}
        if 'project_key' in params:
            path_params['projectKey'] = params['project_key']
        if 'environment_key' in params:
            path_params['environmentKey'] = params['environment_key']

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['Token']

        return self.api_client.call_api('/environments/{projectKey}/{environmentKey}', 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='Environment',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def patch_environment(self, project_key, environment_key, patch_delta, **kwargs):
        """
        Modify an environment by ID
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.patch_environment(project_key, environment_key, patch_delta, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str project_key: The project key, used to tie the flags together under one project so they can be managed together. (required)
        :param str environment_key: The environment key (required)
        :param list[PatchDelta] patch_delta: http://jsonpatch.com/ (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.patch_environment_with_http_info(project_key, environment_key, patch_delta, **kwargs)
        else:
            (data) = self.patch_environment_with_http_info(project_key, environment_key, patch_delta, **kwargs)
            return data

    def patch_environment_with_http_info(self, project_key, environment_key, patch_delta, **kwargs):
        """
        Modify an environment by ID
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.patch_environment_with_http_info(project_key, environment_key, patch_delta, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str project_key: The project key, used to tie the flags together under one project so they can be managed together. (required)
        :param str environment_key: The environment key (required)
        :param list[PatchDelta] patch_delta: http://jsonpatch.com/ (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['project_key', 'environment_key', 'patch_delta']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method patch_environment" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'project_key' is set
        if ('project_key' not in params) or (params['project_key'] is None):
            raise ValueError("Missing the required parameter `project_key` when calling `patch_environment`")
        # verify the required parameter 'environment_key' is set
        if ('environment_key' not in params) or (params['environment_key'] is None):
            raise ValueError("Missing the required parameter `environment_key` when calling `patch_environment`")
        # verify the required parameter 'patch_delta' is set
        if ('patch_delta' not in params) or (params['patch_delta'] is None):
            raise ValueError("Missing the required parameter `patch_delta` when calling `patch_environment`")


        collection_formats = {}

        path_params = {}
        if 'project_key' in params:
            path_params['projectKey'] = params['project_key']
        if 'environment_key' in params:
            path_params['environmentKey'] = params['environment_key']

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'patch_delta' in params:
            body_params = params['patch_delta']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['Token']

        return self.api_client.call_api('/environments/{projectKey}/{environmentKey}', 'PATCH',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type=None,
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def post_environment(self, project_key, environment_body, **kwargs):
        """
        Create an environment
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.post_environment(project_key, environment_body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str project_key: The project key, used to tie the flags together under one project so they can be managed together. (required)
        :param EnvironmentBody environment_body: New environment (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.post_environment_with_http_info(project_key, environment_body, **kwargs)
        else:
            (data) = self.post_environment_with_http_info(project_key, environment_body, **kwargs)
            return data

    def post_environment_with_http_info(self, project_key, environment_body, **kwargs):
        """
        Create an environment
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.post_environment_with_http_info(project_key, environment_body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str project_key: The project key, used to tie the flags together under one project so they can be managed together. (required)
        :param EnvironmentBody environment_body: New environment (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['project_key', 'environment_body']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method post_environment" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'project_key' is set
        if ('project_key' not in params) or (params['project_key'] is None):
            raise ValueError("Missing the required parameter `project_key` when calling `post_environment`")
        # verify the required parameter 'environment_body' is set
        if ('environment_body' not in params) or (params['environment_body'] is None):
            raise ValueError("Missing the required parameter `environment_body` when calling `post_environment`")


        collection_formats = {}

        path_params = {}
        if 'project_key' in params:
            path_params['projectKey'] = params['project_key']

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'environment_body' in params:
            body_params = params['environment_body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['Token']

        return self.api_client.call_api('/environments/{projectKey}', 'POST',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type=None,
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)
